package proxy

import "strings"

// This describes the existing append API; it does not validate referenced runs,
// deduplicate evidence, change promotion rules or introduce raw-view gating.
func enrichSkillFitnessOpenAPIOperation(method string, op, responses map[string]any) {
	appError := func(description string) map[string]any {
		return map[string]any{"description": description, "content": jsonContent(schemaRef("AppError"))}
	}
	responses["401"] = appError("invalid_api_key: GET requires admin read scope; POST requires admin write scope. Existing admin-read access includes note and reference text; no separate raw-prompt permission is applied.")
	responses["405"] = appError("method_not_allowed: only GET and POST are supported")
	if strings.EqualFold(method, "get") {
		parameters, _ := op["parameters"].([]any)
		op["parameters"] = append(parameters, map[string]any{
			"name": "skill", "in": "query", "required": true,
			"schema":      map[string]any{"type": "string", "minLength": 1},
			"description": "Skill name after Go TrimSpace; blank names are rejected. Names are not otherwise normalized or required to exist in the skill registry.",
		})
		op["description"] = "Returns confirmed evidence rows and the number of passing rows for the exact Go-trimmed skill name. An unknown skill returns an empty array, not 404. Duplicate references count as separate rows. required is the existing production-gate threshold, not a claim that this skill requires the gate or can be promoted. Listing performs no model execution, reference verification or promotion."
		responses["200"] = successResponse("SkillFitnessResponse")
		responses["400"] = appError("missing_skill: skill query parameter is blank")
		responses["500"] = appError("list_failed: no confirmed evidence snapshot")
		return
	}
	// The generic endpoint template advertises 200, but this existing handler
	// returns only 201 on a successful append.
	delete(responses, "200")
	op["requestBody"] = requestBody("SkillFitnessAppendRequest")
	op["description"] = "Appends one new evidence row on every successful request, including duplicate references; no idempotency or automatic retry guarantee is provided. The skill and reference need not exist and are not verified. kind is Go-trimmed and defaults to multimodel when omitted, null or unrecognized. Omitted/null passed is false and omitted/null score is 0; zero is a real recorded score, not an unscored marker. Skill, reference and note are Go-trimmed; names are otherwise opaque. Success returns the submitted row with created_at empty under the existing legacy contract; GET returns the timestamp generated by storage. created_by is the existing skill actor, whereas audit uses its existing pseudonymous token actor and kind/passed/ref payload. Audit is post-write best-effort, not atomic. Recording does not execute a model or promote a skill."
	responses["201"] = successResponse("SkillFitnessRecordedResponse")
	responses["400"] = appError("bad_request: invalid JSON, incompatible field types or blank skill; no row appended")
	responses["500"] = appError("add_failed: evidence could not be stored")
}

func skillFitnessOpenAPISchemas() map[string]any {
	rowFields := func(createdAt map[string]any) map[string]any {
		return map[string]any{
			"id":         map[string]any{"type": "string", "minLength": 1},
			"skill_name": map[string]any{"type": "string", "minLength": 1},
			"kind":       map[string]any{"type": "string", "description": "Known kinds are multimodel, golden and testcase. Existing stored values are not rewritten."},
			"ref_id":     map[string]any{"type": "string"},
			"passed":     map[string]any{"type": "boolean"},
			"score":      map[string]any{"type": "number", "format": "double", "description": "Recorded finite score, including zero, negative values and fractional values; no 0–100 range is imposed by this API."},
			"note":       map[string]any{"type": "string"},
			"created_by": map[string]any{"type": "string", "description": "Existing skill actor, normally the JWT subject; distinct from the pseudonymous admin audit actor."},
			"created_at": createdAt,
		}
	}
	required := []string{"id", "skill_name", "kind", "ref_id", "passed", "score", "note", "created_by", "created_at"}
	storedTime := map[string]any{"type": "string", "format": "date-time"}
	recordedTime := map[string]any{
		"description": "Legacy successful POST returns an empty timestamp. A persisted timestamp is read via GET; do not treat the empty 201 timestamp as a failed append and retry.",
		"oneOf":       []any{map[string]any{"type": "string", "enum": []string{""}}, storedTime},
	}
	return map[string]any{
		"SkillFitnessEvidence":         map[string]any{"type": "object", "required": required, "properties": rowFields(storedTime)},
		"SkillFitnessRecordedResponse": map[string]any{"type": "object", "required": required, "properties": rowFields(recordedTime)},
		"SkillFitnessResponse": map[string]any{
			"type": "object", "required": []string{"skill", "evidence", "passing_count", "required"},
			"properties": map[string]any{
				"skill":         map[string]any{"type": "string", "minLength": 1},
				"evidence":      map[string]any{"type": "array", "items": schemaRef("SkillFitnessEvidence")},
				"passing_count": map[string]any{"type": "integer", "minimum": 0},
				"required":      map[string]any{"type": "integer", "minimum": 0, "description": "Existing gate threshold; not a per-skill promotion-readiness decision."},
			},
		},
		"SkillFitnessAppendRequest": map[string]any{
			"type": "object", "required": []string{"skill"},
			"properties": map[string]any{
				"skill":  map[string]any{"type": "string", "minLength": 1, "description": "Must remain nonblank after Go TrimSpace; not required to exist."},
				"kind":   map[string]any{"type": "string", "nullable": true, "description": "multimodel, golden or testcase; omitted/null/unknown values normalize to multimodel, not an enum validation error."},
				"ref_id": map[string]any{"type": "string", "nullable": true},
				"passed": map[string]any{"type": "boolean", "nullable": true, "default": false},
				"score":  map[string]any{"type": "number", "format": "double", "nullable": true, "default": 0},
				"note":   map[string]any{"type": "string", "nullable": true},
			},
		},
	}
}
